odometry:
  extraction: "sift"          # Feature Extraction Algorithm (orb, sift, surf)
  matching: "bf"              # Feature Matching Algorithm (bf, flann)
  pose: "pnp"                 # Pose Estimation Algorithm (pnp, emat)

camera:
  accel-threshold: 0.3       # Acceleration threshold for detection of camera movement 
  gyro-threshold: 0.4        # Gyroscope threshold for detection of camera movement
  replay: true             # Enable replay from rosbag
  path: "/home/angelo/Projects/EagleTRT/cone-localization/2025_04_26_18_46_13_baseline_Povo.bag"  # Path to the rosbag (if replay is on)
# TODO: add camera configuration parameters

yolo:
  enabled: false              # Whether to run YOLO inference
  path: "path/to/model.onnx"  # Path to the YOLO model (if enabled)

telemetry:
  enabled: false               # Enable telemetry communication
  host : "api.eagletrt.it"          # Host for telemetry communication ["localhost" / "api.eagletrt.it" / "control.local"]
  vehicle_id: "nicolo"       # Vehicle ID for telemetry

debug: false                   # Enable debug mode, ence print the debug information
display: true                 # Display the RGB and depth from camera, as well as features matching done
